plugins { id 'com.android.application' }

android {
    namespace 'jp.shunataro.burrow'
    compileSdk 35
    defaultConfig {
        applicationId 'jp.shunataro.burrow'
        minSdk 26
        targetSdk 35
        versionCode (System.getenv('GITHUB_RUN_NUMBER') ?: '1').toInteger()
        versionName '1.0.' + (System.getenv('GITHUB_RUN_NUMBER') ?: '0')
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies { implementation 'androidx.webkit:webkit:1.12.1' }
